name: AWS Static Site

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      FULLY_QUALIFIED_DOMAIN: "lukewiwa.com"
      SUB_DOMAIN: "pwa-share-target-revealer"
      AWS_DEFAULT_REGION: "ap-southeast-2"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: install deps
        run: npm ci

      - name: install infra deps
        working-directory: infra
        run: npm ci

      - name: deploy
        run: npm run build && npm --prefix=infra run deploy
